[package]
name = "sb-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order"] }
tokio = { version = "1", features = ["io-util", "sync", "time", "macros", "rt"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }

[dev-dependencies]
tokio = { version = "1", features = ["io-util", "sync", "time", "macros", "rt", "rt-multi-thread", "test-util"] }
tempfile = "3"
